
import Head from "next/head";
import React from "react";



export default function Home() {
  // console.log(allPosts);
  return (
    <div className="container h-full w-full mx-auto pt-10">
      <Head>
        <title className="font-serif">Shin's Code'</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className="container w-full mt-16 ">
        <h1 className="text-5xl font-medium text-center mb-16">
          Shin's Code
        </h1>
  
      </main>
    </div>
  );
}
